Fix compiling with spaces in paths (#1396)
Fixes #1393.

Two issues:
1. SwiftLint doesn't support spaces in the config path (seemingly as of 0.42.0, see realm/SwiftLint#3471)

```bash
> Pods/SwiftLint/swiftlint --config "/Users/zac/Sources/hass ios/.swiftlint.yml"
error: SwiftLint Configuration Error: Could not read file at path: /Users/zac/Sources/hass
```

2. We were invoking it and passing things without spaces around the paths.